### ISSUE TITLE
The door to the ammunition workbench in Blackrock wont unlock after the code is typed in

### ISSUE THREAD

**Issue by SamimiesGames** [Filigrani/SkyCoop#43] opened 2022-11-28 04:25 UTC
**Mod Version:** v0.10.4 
**Game Version:** v20.2  
**Launcher:** Steam  
**Additional mods installed:** Yes DeveloperConsole
**Perspective:** Both

### Description
The door to the ammunition workbench won't unlock after the code is typed in the keypad during an aurora.

### How to reproduce
1. Host or client.
2. On region 'BlackrockPrisonSurvivalZone'
3. Try to open the ammunition workbench door with the code from the mine (3445). Click the keypad next to the door during an aurora.
4. The door is still locked.

### Expected behaviour
The door should have been unlocked after the code is typed during an aurora.

Additional note for a possible fix:
[05:44:09.516] [Sky_Co-op] [Papers codes] Interact with keypad that has code: 3008
When the actual code is 3445.

### Logs

**Host side log**
[MelonLoader_22-11-28_05-24-25.213.log](https://github.com/Filigrani/SkyCoop/files/10100444/MelonLoader_22-11-28_05-24-25.213.log)

**Client side log**
[MelonLoader_22-11-27_22-25-44.565.log](https://github.com/Filigrani/SkyCoop/files/10100438/MelonLoader_22-11-27_22-25-44.565.log)

**Comment by Filigrani** [comment] 2022-11-28 08:57
I can't see problem by logs. You have code for that keypad. It all looks like it should open. Also I am sure I been tested it few weeks ago, it was working flawless. What exact result you have? Keypad does green light, but door wont open? Or keypad still does red?

**Comment by SamimiesGames** [comment] 2022-11-28 10:01
Hey, Filigrani!

The keypad lits up green, but the door is still locked.

Here's a short video about the issue.
https://youtu.be/2bZ98x6Vm1E

**Comment by Filigrani** [comment] 2022-11-28 12:04
Oh I see what wrong here. You have input keypad password right, earlier. So keypad inactive now, and can't remove lock from the door once again. Looks like you have input password before, and saved with leaving this door closed. This I was able to reproduce this. This door has automatic close trigger when you enter or far away, I think this not properly saved in multiplayer

**Comment by Filigrani** [comment] 2022-11-28 12:17
So actual steps to reproduce:
1. Get password and aurora.
2. Open the door.
3. Save, and then re-join/re-host.
4. Result: Keypad with green light, and closed door.

Now I wonder if that happends in vanila aswell.
https://youtu.be/sa21NGaaz14

**Comment by Filigrani** [comment] 2023-01-15 14:25
Fixed in latest release.

**Closed by Filigrani** 2023-01-15 14:25 UTC
Labels: bug, going to be fixed in next release
